---
version: "2.1"
services:
    code-server:
        image: lscr.io/linuxserver/code-server
        container_name: code-server
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Denver
          - PASSWORD=sanitized password
          - DEFAULT_WORKSPACE=/config/workspace
        volumes:
          - /*location*/codeserv/code:/config
        ports:
          - 8443:8443
        restart: unless-stopped
