version: "3"

services:
  db:
    image: lscr.io/linuxserver/mariadb
    restart: always
    environment:
      - TZ=America/Denver
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=santized password
    volumes:
      - /*location*/photoview/mysql:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:latest
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache

    volumes:
      - /*location*/photoview/cache:/app/cache
      - /*location*/filebrowser/srv/users/jd/pictures:/photos:ro
